### ISSUE TITLE
IE8 compatibility: Avoid reserved words

### ISSUE THREAD

**Issue by Shepard** [eemeli/make-plural.js#9]
IE8 does not allow using reserved words as property names. Currently this leads to a parsing error in plurals.js for the code "in". Simply wrapping this property name in quotes makes it work in IE8 as well.

So the line

    in: _cp[0],

becomes

    "in": _cp[0],

Since I have to support IE8 I simply did this in my compiled copy of plurals.js but I'm not sure how to fix the actual compilation mechanism. I guess it could match the code names against a list of two-letter and three-letter reservered words and quote them if necessary.

**Comment by eemeli** [comment]
Thank you or reporting this; I added a special check for the `in` keyword and pushed out a new minor release.

**Comment by Shepard** [comment]
Wow, thanks for the quick response and the prompt fix. Much appreciated!
